// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using si.gapi.samples.jsonDb.context;

#nullable disable

namespace si.gapi.samples.jsonDb.context.migrations
{
    [DbContext(typeof(JsonDbCtx))]
    partial class JsonDbCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107");

            modelBuilder.Entity("si.gapi.samples.jsonDb.models.PersonDb", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("modifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("id");

                    b.HasIndex("id");

                    b.HasIndex("firstName", "lastName");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("si.gapi.samples.jsonDb.models.PersonDb", b =>
                {
                    b.OwnsMany("si.gapi.samples.jsonDb.models.Address", "addressListOne", b1 =>
                        {
                            b1.Property<int>("PersonDbid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("city")
                                .IsRequired();

                            b1.Property<string>("street")
                                .IsRequired();

                            b1.Property<string>("type")
                                .IsRequired();

                            b1.Property<string>("zip")
                                .IsRequired();

                            b1.HasKey("PersonDbid", "__synthesizedOrdinal");

                            b1.ToTable("persons");

                            b1.ToJson("addressListOne");

                            b1.WithOwner()
                                .HasForeignKey("PersonDbid");
                        });

                    b.OwnsMany("si.gapi.samples.jsonDb.models.Address", "addressListTwo", b1 =>
                        {
                            b1.Property<int>("PersonDbid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("city")
                                .IsRequired();

                            b1.Property<string>("street")
                                .IsRequired();

                            b1.Property<string>("type")
                                .IsRequired();

                            b1.Property<string>("zip")
                                .IsRequired();

                            b1.HasKey("PersonDbid", "__synthesizedOrdinal");

                            b1.ToTable("persons");

                            b1.ToJson("addressListTwo");

                            b1.WithOwner()
                                .HasForeignKey("PersonDbid");
                        });

                    b.OwnsOne("si.gapi.samples.jsonDb.models.Address", "addressPrimary", b1 =>
                        {
                            b1.Property<int>("PersonDbid");

                            b1.Property<string>("city")
                                .IsRequired();

                            b1.Property<string>("street")
                                .IsRequired();

                            b1.Property<string>("type")
                                .IsRequired();

                            b1.Property<string>("zip")
                                .IsRequired();

                            b1.HasKey("PersonDbid");

                            b1.ToTable("persons");

                            b1.ToJson("addressPrimary");

                            b1.WithOwner()
                                .HasForeignKey("PersonDbid");
                        });

                    b.Navigation("addressListOne");

                    b.Navigation("addressListTwo");

                    b.Navigation("addressPrimary")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
